from decouple import config

class Settings:
	POSTGRES_NAME=config('POSTGRES_NAME')
	POSTGRES_USER=config('POSTGRES_USER')
	POSTGRES_PASS=config('POSTGRES_PASS')
	POSTGRES_HOST=config('POSTGRES_HOST')
	
	JWT_ALGORITHM=config('JWT_ALGORITHM')
	ACCESS_TOKEN_EXPIRES=config('ACCESS_TOKEN_EXPIRES')
	REFRESH_TOKEN_EXPIRES=config('REFRESH_TOKEN_EXPIRES')	
	JWT_PRIVATE_KEY=config('JWT_PRIVATE_KEY')
	JWT_PUBLIC_KEY=config('JWT_PUBLIC_KEY')

	EMAIL_HOST = config('EMAIL_HOST')
	EMAIL_PORT = config('EMAIL_PORT')
	EMAIL_USER = config('EMAIL_USER')
	EMAIL_PASS = config('EMAIL_PASS')
	EMAIL_FROM = config('EMAIL_FROM')
	EMAIL_TOKEN_EXPIRES_SECONDS = config('EMAIL_TOKEN_EXPIRES_SECONDS')
settings = Settings()