version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    env_file:
      - ./fastapi_app/.env.prod

  react:
    build:
      context: ./react/app
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - '3000:3000'