"""add password token to users

Revision ID: 0980daa11c71
Revises: 01d56a550a6e
Create Date: 2022-10-28 09:56:43.423438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0980daa11c71'
down_revision = '01d56a550a6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['password_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password_token')
    # ### end Alembic commands ###
