"""Create library record/tag + associate table

Revision ID: 3dc4d5da6ae1
Revises: 68232d29b04d
Create Date: 2022-12-03 01:32:55.823277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3dc4d5da6ae1'
down_revision = '68232d29b04d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_record',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('library_tag',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_records_tags',
    sa.Column('library_record_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('library_tag_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['library_record_id'], ['library_record.id'], ),
    sa.ForeignKeyConstraint(['library_tag_id'], ['library_tag.id'], ),
    sa.PrimaryKeyConstraint('library_record_id', 'library_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library_records_tags')
    op.drop_table('library_tag')
    op.drop_table('library_record')
    # ### end Alembic commands ###
