"""Create quest_line/quest_option tables

Revision ID: 6685cc382ce4
Revises: ff9c1502a9f3
Create Date: 2022-12-16 21:49:28.818713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6685cc382ce4'
down_revision = 'ff9c1502a9f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
