"""Update QuestOption with foreign key

Revision ID: 66d45408bbaa
Revises: 780a3d2d6bda
Create Date: 2022-12-16 23:26:03.923060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66d45408bbaa'
down_revision = '780a3d2d6bda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest_option', sa.Column('quest_next_line_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'quest_option', 'quest_line', ['quest_next_line_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quest_option', type_='foreignkey')
    op.drop_column('quest_option', 'quest_next_line_id')
    # ### end Alembic commands ###
