"""Create quest_line/quest_option tables fix bug

Revision ID: 780a3d2d6bda
Revises: 6685cc382ce4
Create Date: 2022-12-16 22:38:49.477951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '780a3d2d6bda'
down_revision = '6685cc382ce4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_option',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('unique_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='quest_option_pkey'),
    sa.UniqueConstraint('unique_name', name='quest_option_unique_name_key')
    )
    op.create_table('quest_line',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unique_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='quest_line_pkey'),
    sa.UniqueConstraint('unique_name', name='quest_line_unique_name_key')
    )
    op.create_table('quest_lines_options',
    sa.Column('quest_line_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('quest_option_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quest_line_id'], ['quest_line.id'], name='quest_lines_options_quest_line_id_fkey'),
    sa.ForeignKeyConstraint(['quest_option_id'], ['quest_option.id'], name='quest_lines_options_quest_option_id_fkey'),
    sa.PrimaryKeyConstraint('quest_line_id', 'quest_option_id', name='quest_lines_options_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quest_lines_options')
    op.drop_table('quest_option')
    op.drop_table('quest_line')
    # ### end Alembic commands ###
