"""create comments model

Revision ID: 87b1882d8a3e
Revises: b0ba2b7d9dfc
Create Date: 2022-11-22 01:25:02.374796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b1882d8a3e'
down_revision = 'b0ba2b7d9dfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text_comment', sa.TEXT(), nullable=True))
    op.add_column('comments', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('comments', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('comments', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'created_at')
    op.drop_column('comments', 'text_comment')
    # ### end Alembic commands ###
