"""Update Quest tables

Revision ID: 89681a26c730
Revises: 66d45408bbaa
Create Date: 2022-12-19 19:09:58.397601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89681a26c730'
down_revision = '66d45408bbaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest_line', sa.Column('unique_number', sa.Integer(), nullable=True))
    op.add_column('quest_line', sa.Column('quest_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('quest_line_unique_name_key', 'quest_line', type_='unique')
    op.create_foreign_key(None, 'quest_line', 'quests', ['quest_id'], ['id'], ondelete='CASCADE')
    op.drop_column('quest_line', 'unique_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest_line', sa.Column('unique_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quest_line', type_='foreignkey')
    op.create_unique_constraint('quest_line_unique_name_key', 'quest_line', ['unique_name'])
    op.drop_column('quest_line', 'quest_id')
    op.drop_column('quest_line', 'unique_number')
    # ### end Alembic commands ###
