"""Change quest option table

Revision ID: c61a0e634166
Revises: 89681a26c730
Create Date: 2023-01-01 23:51:49.316612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61a0e634166'
down_revision = '89681a26c730'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest_option', sa.Column('name', sa.String(), nullable=True))
    op.drop_constraint('quest_option_unique_name_key', 'quest_option', type_='unique')
    op.drop_column('quest_option', 'description')
    op.drop_column('quest_option', 'unique_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest_option', sa.Column('unique_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('quest_option', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('quest_option_unique_name_key', 'quest_option', ['unique_name'])
    op.drop_column('quest_option', 'name')
    # ### end Alembic commands ###
