"""UNDO quest_next_line from quest option are nullable for delete cascade

Revision ID: d814c45ebbba
Revises: a1a8a7e421a7
Create Date: 2023-01-10 01:13:45.662375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd814c45ebbba'
down_revision = 'a1a8a7e421a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quest_option', 'quest_next_line_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quest_option', 'quest_next_line_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
