"""add is_activated in quest

Revision ID: facc9bbf6be3
Revises: d814c45ebbba
Create Date: 2023-01-21 05:12:42.853558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'facc9bbf6be3'
down_revision = 'd814c45ebbba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('is_activated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'is_activated')
    # ### end Alembic commands ###
