"""Library tag unique name

Revision ID: ff9c1502a9f3
Revises: 3dc4d5da6ae1
Create Date: 2022-12-05 17:37:12.897041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9c1502a9f3'
down_revision = '3dc4d5da6ae1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'library_tag', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'library_tag', type_='unique')
    # ### end Alembic commands ###
